--- 
:staging_dir: ./stage
:log_dir: ./log
:dspace: 
  :host: https://lirias.kuleuven.be/oai/request
  :urn: "oai:lirias.kuleuven.be:"
:sfx: 
  :rsi: http://librilinks.libis.be/kuleuven/cgi/core/rsi/rsi.cgi
